-- Valoriza schema converted from the legacy MariaDB dump.
-- Data is intentionally not imported here; use a reviewed migration for production data.

create table if not exists public.tbl_empresas (
  id bigint generated by default as identity primary key,
  cnpj varchar(18) not null,
  razao_social varchar(255) not null,
  nome_fantasia varchar(255), email varchar(150), telefone varchar(20),
  data_abertura date, capital_social numeric(15,2), cep char(8), estado varchar(100),
  cidade varchar(100), bairro varchar(150), endereco varchar(255), numero varchar(20),
  complemento varchar(150), logo varchar(255),
  data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now(),
  status_sistema varchar(20) not null default 'incluido', cadastrado_por bigint, atualizado_por bigint
);

create table if not exists public.tbl_usuarios (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id),
  nome_completo varchar(255) not null, email varchar(150) not null, telefone varchar(20),
  senha varchar(255) not null, perfil_acesso varchar(30) not null default 'operador',
  ativo boolean not null default true, notificar_contratos boolean not null default false,
  avatar varchar(255), data_cadastro timestamptz not null default now(),
  data_atualizacao timestamptz not null default now(), status_sistema varchar(20) not null default 'incluido'
);

create table if not exists public.tbl_bancos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id),
  banco varchar(100) not null, agencia varchar(20) not null, conta varchar(30) not null,
  chave_pix varchar(150), padrao boolean default false,
  data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now(),
  status_sistema varchar(20) not null default 'incluido', cadastrado_por bigint, atualizado_por bigint
);

create table if not exists public.tbl_configuracoes_contratos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id),
  taxa_juros_minima_sem_garantia numeric(5,2) default 0,
  taxa_juros_avalista numeric(5,2) default 0, taxa_juros_imovel numeric(5,2) default 0,
  taxa_juros_veiculo numeric(5,2) default 0, taxa_juros_outras_garantias numeric(5,2) default 0,
  taxa_iof numeric(10,6), limite_prorrogacoes integer default 12,
  qtd_minima_parcelas integer default 1, qtd_maxima_parcelas integer default 12,
  tipo_registro_crdc varchar(30) default 'manual', crdc_usuario varchar(255), crdc_senha varchar(255),
  crdc_cnpj varchar(18), dias_notificacao_vencimento varchar(255),
  notificar_vencimento_email boolean default false, notificar_vencimento_whatsapp boolean default false,
  exibir_notificacoes_vencimento boolean default false, frequencia_notificacao_atraso varchar(50),
  notificar_atraso_email boolean default false, notificar_atraso_whatsapp boolean default false,
  exibir_notificacoes_atraso boolean default false, copiar_avalistas_atraso varchar(50),
  cadastrado_por bigint, atualizado_por bigint, data_cadastro timestamptz not null default now(),
  data_atualizacao timestamptz not null default now(), status_sistema varchar(20) not null default 'incluido'
);

create table if not exists public.tbl_pessoas_fisicas (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id), nome_completo varchar(255) not null,
  cpf varchar(14) not null, rg varchar(20), orgao_emissor_rg varchar(50), telefone varchar(20),
  email varchar(150), rede_social varchar(255), cep char(8), estado varchar(100), cidade varchar(100),
  bairro varchar(150), endereco varchar(255), numero varchar(20), complemento varchar(150),
  renda_mensal numeric(12,2), limite_credito numeric(12,2) default 0, estado_civil varchar(30),
  regime_partilha varchar(50), observacao text, banco varchar(100), agencia varchar(20), conta varchar(30),
  chave_pix varchar(150), data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now(),
  cadastrado_por bigint, atualizado_por bigint, status_sistema varchar(20) not null default 'incluido'
);

create table if not exists public.tbl_pessoas_juridicas (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id), razao_social varchar(255) not null,
  nome_fantasia varchar(255), cnpj varchar(20) not null, telefone varchar(20), email varchar(150),
  rede_social varchar(255), cep char(8), estado varchar(100), cidade varchar(100), bairro varchar(150),
  endereco varchar(255), numero varchar(20), complemento varchar(150), limite_credito numeric(12,2) default 0,
  observacao text, banco varchar(100), agencia varchar(20), conta varchar(30), chave_pix varchar(150),
  data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now(),
  cadastrado_por bigint, atualizado_por bigint, status_sistema varchar(20) not null default 'incluido'
);

create table if not exists public.tbl_contratos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id), numero_contrato varchar(50),
  tipo_operacao varchar(50) not null default 'Empréstimo', valor_solicitado numeric(15,2) not null,
  periodo_amortizacao varchar(50) not null, modelo_amortizacao varchar(50) not null,
  taxa_juros numeric(10,6) not null, tipo_taxa varchar(20) not null default 'mensal',
  quantidade_parcelas integer not null, data_assinatura date not null, data_primeira_parcela date not null,
  simples_nacional boolean not null default false, calcular_iof boolean not null default false,
  tipo_cliente varchar(5) not null default 'pj', cliente_id bigint, juros_mora numeric(10,6),
  multa_moratoria numeric(10,6), risco_inadimplencia varchar(20) default 'Baixo',
  permitir_carencia boolean not null default false, limite_carencia integer, usos_carencia integer not null default 0,
  tipo_assinatura varchar(60) default 'sem_assinatura', enviar_registradora boolean not null default false,
  contrato_iniciado boolean not null default false, status varchar(30) not null default 'Ativo',
  data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now(),
  status_sistema varchar(20) not null default 'incluido', cadastrado_por bigint, atualizado_por bigint
);

create table if not exists public.tbl_contratos_garantias (
  id bigint generated by default as identity primary key,
  contrato_id bigint not null references public.tbl_contratos(id), empresa_id bigint not null references public.tbl_empresas(id),
  tipo_garantia varchar(50) not null, tipo_pessoa_garantia varchar(2) default 'pf', pessoa_id_garantia bigint,
  nome_completo varchar(255), cpf varchar(20), rg varchar(30), orgao_emissor_rg varchar(50), email varchar(255),
  telefone varchar(30), renda_mensal numeric(15,2), estado_civil varchar(50), regime_bens varchar(50),
  cep varchar(10), estado varchar(5), cidade varchar(100), bairro varchar(100), endereco varchar(255), numero varchar(20),
  complemento varchar(100), tabelionato varchar(255), numero_matricula varchar(255), proprietario varchar(255),
  fabricante varchar(255), modelo varchar(255), ano_fabricacao varchar(10), ano_modelo varchar(10), chassi varchar(50),
  renavam varchar(20), placa varchar(10), cor varchar(50), outros_dados text, tipo_recebivel varchar(100),
  numero_identificacao varchar(255), sacado varchar(255), data_vencimento_recebivel date, descricao text,
  numero_serie varchar(100), estado_conservacao varchar(100), localizacao_fisica varchar(255), valor_avaliacao numeric(15,2),
  data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now(),
  status_sistema varchar(20) not null default 'incluido', cadastrado_por bigint, atualizado_por bigint
);

create table if not exists public.tbl_contratos_parcelas (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id), contrato_id bigint not null references public.tbl_contratos(id),
  numero_parcela integer not null, valor_parcela numeric(15,2) not null, data_vencimento date not null,
  valor_juros numeric(15,2) default 0, valor_amortizacao numeric(15,2) default 0, saldo_devedor numeric(15,2) default 0,
  status_sistema varchar(50) default 'incluido', data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now()
);

create table if not exists public.tbl_receitas (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id), data_recebimento date, data_vencimento date,
  descricao varchar(255), valor_recebido numeric(15,2) default 0, conta_bancaria_destino_id bigint,
  tipo_pagador varchar(50), tipo_pessoa varchar(10), pagador_id bigint, nome_pagador_manual varchar(255),
  tipo_comprovante_fiscal varchar(100), numero_comprovante varchar(100), categoria_id bigint,
  forma_recebimento varchar(100), status varchar(50) default 'Pendente', observacoes text, contrato_id bigint references public.tbl_contratos(id),
  parcela_numero integer, status_sistema varchar(50) default 'incluido', data_cadastro timestamptz not null default now(),
  data_atualizacao timestamptz not null default now(), cadastrado_por bigint, atualizado_por bigint
);

create table if not exists public.tbl_receitas_prorrogacoes (
  id bigint generated by default as identity primary key,
  receita_id bigint not null references public.tbl_receitas(id), contrato_id bigint references public.tbl_contratos(id),
  empresa_id bigint not null references public.tbl_empresas(id), numero_contrato varchar(50), parcela_numero integer,
  total_parcelas integer, cliente_nome varchar(255), cliente_documento varchar(30), data_vencimento_anterior date not null,
  data_vencimento_nova date not null, valor_anterior numeric(15,2) not null default 0, valor_recebido numeric(15,2) not null default 0,
  desconto numeric(15,2) not null default 0, juros_atualizacao numeric(15,2) not null default 0, juros_mora numeric(15,2) not null default 0,
  multa_atraso numeric(15,2) not null default 0, valor_devido numeric(15,2) not null default 0, valor_novo numeric(15,2) not null default 0,
  justificativa text, cadastrado_por bigint, data_cadastro timestamptz not null default now(), status_sistema varchar(20) default 'incluido'
);

create table if not exists public.tbl_despesas (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.tbl_empresas(id), data_pagamento date, data_vencimento date,
  descricao varchar(255) not null, valor_pago numeric(15,2) not null default 0, conta_bancaria_origem_id bigint,
  tipo_favorecido varchar(20) not null default 'cadastrado', tipo_pessoa varchar(2), favorecido_id bigint,
  nome_favorecido_manual varchar(255), tipo_comprovante_fiscal varchar(100), numero_comprovante varchar(100), categoria_id bigint,
  forma_pagamento varchar(100), status varchar(50) default 'Pendente', irrf_retido numeric(15,2) default 0,
  inss_retido numeric(15,2) default 0, iss_retido numeric(15,2) default 0, outros_impostos_retidos numeric(15,2) default 0,
  observacoes text, despesa_recorrente boolean default false, quantidade_despesas_recorrentes integer,
  data_cadastro timestamptz not null default now(), data_atualizacao timestamptz not null default now(),
  status_sistema varchar(20) not null default 'incluido', cadastrado_por bigint, atualizado_por bigint
);

create index if not exists idx_usuarios_empresa on public.tbl_usuarios(empresa_id);
create index if not exists idx_contratos_empresa on public.tbl_contratos(empresa_id);
create index if not exists idx_contratos_parcelas_contrato on public.tbl_contratos_parcelas(contrato_id);
create index if not exists idx_receitas_empresa on public.tbl_receitas(empresa_id);
create index if not exists idx_despesas_empresa on public.tbl_despesas(empresa_id);
