-- Rate limit de login que sobrevive ao serverless.
--
-- O @fastify/rate-limit guarda contadores em memória: na Vercel cada instância tem os
-- seus e elas são efêmeras, então o limite de 5/minuto no login nunca chegou a barrar
-- força bruta de verdade. Contar as tentativas no banco dá um estado compartilhado
-- entre todas as instâncias.
--
-- Só falhas são registradas, e um login bem-sucedido apaga as do e-mail.
create table if not exists public.tbl_tentativas_login (
  id bigint generated by default as identity primary key,
  email varchar(150) not null,
  ip varchar(60),
  criado_em timestamptz not null default now()
);

create index if not exists idx_tentativas_login_email_criado
  on public.tbl_tentativas_login (email, criado_em desc);
